---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: login auth
      responses:
        '200':
          description: successful
  "/api/v1/logout":
    delete:
      summary: logout auth
      responses:
        '200':
          description: successful
  "/api/v1/test":
    get:
      summary: list tests
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
